module.exports = {
  // The keys here don't matter, as long as they are unique
  lego: [{ type: "autogenerated", dirName: "lego" }],
  rcj: [{ type: "autogenerated", dirName: "rcj" }],
  others: [{ type: "autogenerated", dirName: "others" }],
};
